create table retail_stores (
  store_id number generated by default as identity primary key,
  store_code varchar2(24) not null unique,
  store_name varchar2(120) not null,
  region_name varchar2(40) not null,
  city varchar2(80) not null,
  state_code varchar2(2) not null,
  store_format varchar2(30) not null,
  status varchar2(20) default 'OPEN' not null,
  opened_on date default sysdate not null,
  constraint retail_stores_status_ck check (status in ('OPEN', 'REMODEL', 'CLOSED'))
);

create table retail_warehouses (
  warehouse_id number generated by default as identity primary key,
  warehouse_code varchar2(24) not null unique,
  warehouse_name varchar2(120) not null,
  region_name varchar2(40) not null,
  city varchar2(80) not null,
  state_code varchar2(2) not null,
  capacity_units number not null,
  status varchar2(20) default 'ACTIVE' not null,
  constraint retail_warehouse_status_ck check (status in ('ACTIVE', 'LIMITED', 'OFFLINE'))
);

create table retail_products (
  product_id number generated by default as identity primary key,
  sku varchar2(40) not null unique,
  product_name varchar2(160) not null,
  category varchar2(60) not null,
  subcategory varchar2(80) not null,
  brand varchar2(80) not null,
  unit_cost number(10,2) not null,
  unit_price number(10,2) not null,
  lifecycle_status varchar2(20) default 'ACTIVE' not null,
  constraint retail_product_lifecycle_ck check (lifecycle_status in ('ACTIVE', 'SEASONAL', 'CLEARANCE', 'DISCONTINUED'))
);

create table inventory_positions (
  position_id number generated by default as identity primary key,
  product_id number not null references retail_products(product_id),
  location_type varchar2(20) not null,
  location_id number not null,
  on_hand number not null,
  reserved_qty number default 0 not null,
  reorder_point number not null,
  reorder_qty number not null,
  safety_stock number not null,
  last_updated timestamp default systimestamp not null,
  constraint inventory_location_type_ck check (location_type in ('STORE', 'WAREHOUSE')),
  constraint inventory_nonnegative_ck check (on_hand >= 0 and reserved_qty >= 0 and reorder_point >= 0 and reorder_qty >= 0 and safety_stock >= 0),
  constraint inventory_position_uk unique (product_id, location_type, location_id)
);

create table inventory_events (
  event_id number generated by default as identity primary key,
  product_id number not null references retail_products(product_id),
  location_type varchar2(20) not null,
  location_id number not null,
  event_type varchar2(30) not null,
  quantity_delta number not null,
  reference_id varchar2(80),
  scenario_id number,
  event_ts timestamp default systimestamp not null,
  constraint inventory_events_location_ck check (location_type in ('STORE', 'WAREHOUSE')),
  constraint inventory_events_type_ck check (event_type in ('SALE', 'RETURN', 'RECEIPT', 'TRANSFER_IN', 'TRANSFER_OUT', 'ADJUSTMENT', 'SCENARIO'))
);

create table customer_orders (
  order_id number generated by default as identity primary key,
  order_number varchar2(40) not null unique,
  store_id number not null references retail_stores(store_id),
  order_status varchar2(20) not null,
  order_ts timestamp default systimestamp not null,
  total_amount number(12,2) not null,
  constraint customer_orders_status_ck check (order_status in ('PLACED', 'FULFILLED', 'CANCELLED', 'RETURNED'))
);

create table order_lines (
  line_id number generated by default as identity primary key,
  order_id number not null references customer_orders(order_id),
  product_id number not null references retail_products(product_id),
  quantity number not null,
  unit_price number(10,2) not null,
  constraint order_lines_qty_ck check (quantity > 0)
);

create table replenishment_rules (
  rule_id number generated by default as identity primary key,
  product_id number not null references retail_products(product_id),
  store_id number not null references retail_stores(store_id),
  min_on_hand number not null,
  max_on_hand number not null,
  reorder_qty number not null,
  active_flag char(1) default 'Y' not null,
  constraint replenishment_rules_active_ck check (active_flag in ('Y', 'N')),
  constraint replenishment_rules_qty_ck check (min_on_hand >= 0 and max_on_hand >= min_on_hand and reorder_qty > 0),
  constraint replenishment_rules_uk unique (product_id, store_id)
);

create table inventory_scenarios (
  scenario_id number generated by default as identity primary key,
  scenario_name varchar2(160) not null,
  scenario_type varchar2(40) not null,
  status varchar2(20) default 'DRAFT' not null,
  requested_by varchar2(120) default 'demo-user' not null,
  created_at timestamp default systimestamp not null,
  applied_at timestamp,
  notes varchar2(1000),
  constraint inventory_scenarios_type_ck check (scenario_type in ('DEMAND_SPIKE', 'WAREHOUSE_OUTAGE', 'REPLENISHMENT_RULE', 'STORE_TRANSFER')),
  constraint inventory_scenarios_status_ck check (status in ('DRAFT', 'APPLIED', 'FAILED'))
);

create table scenario_actions (
  action_id number generated by default as identity primary key,
  scenario_id number not null references inventory_scenarios(scenario_id),
  action_type varchar2(40) not null,
  product_id number references retail_products(product_id),
  location_type varchar2(20),
  location_id number,
  quantity_delta number,
  status varchar2(20) default 'PENDING' not null,
  created_at timestamp default systimestamp not null,
  constraint scenario_actions_status_ck check (status in ('PENDING', 'APPLIED', 'FAILED'))
);

create index inventory_positions_location_ix on inventory_positions(location_type, location_id);
create index inventory_positions_product_ix on inventory_positions(product_id);
create index inventory_events_product_ts_ix on inventory_events(product_id, event_ts);
create index inventory_events_location_ts_ix on inventory_events(location_type, location_id, event_ts);
create index orders_store_ts_ix on customer_orders(store_id, order_ts);
create index replenishment_store_ix on replenishment_rules(store_id, active_flag);
