apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory-ops.fullname" . }}-ui-config
  labels:
    {{- include "inventory-ops.labels" . | nindent 4 }}
data:
  config.js: |
    window.__API_BASE_URL__ = "/api";
