{{- if .Values.db.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-ops.dbSecretName" . }}
  labels:
    {{- include "inventory-ops.labels" . | nindent 4 }}
type: Opaque
stringData:
  DB_USER: {{ .Values.db.user | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
  DB_CONNECT_STRING: {{ .Values.db.connectString | quote }}
{{- if .Values.db.tnsAdmin }}
  TNS_ADMIN: {{ .Values.db.tnsAdmin | quote }}
{{- end }}
{{- end }}
