prompt ============================================================================
prompt Retail Inventory Ops demo user setup
prompt Run this script as an administrative user after replacing placeholder values.
prompt ============================================================================

whenever sqlerror exit sql.sqlcode;

prompt Step 1: connect to the source PDB before running user creation statements.
prompt Example:
prompt   alter session set container = <SOURCE_PDB_NAME>;

create user retail_app identified by "<REPLACE_WITH_SECURE_PASSWORD>";

grant create session to retail_app;
grant create table to retail_app;
grant create view to retail_app;
grant create sequence to retail_app;
grant create procedure to retail_app;
grant unlimited tablespace to retail_app;

prompt ============================================================================
prompt Optional: if the user already exists and only needs to be unlocked
prompt ============================================================================
prompt alter user retail_app identified by "<REPLACE_WITH_SECURE_PASSWORD>" account unlock;

prompt ============================================================================
prompt Optional: after creating and opening the thin clone, switch to the clone PDB
prompt and reset identity values if you reseed or add clone-only data manually.
prompt ============================================================================
prompt Example:
prompt   alter session set container = <CLONE_PDB_NAME>;

prompt alter table retail_stores
prompt   modify store_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table retail_warehouses
prompt   modify warehouse_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table retail_products
prompt   modify product_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table inventory_positions
prompt   modify position_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table replenishment_rules
prompt   modify rule_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table customer_orders
prompt   modify order_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table order_lines
prompt   modify line_id generated by default as identity
prompt   (start with limit value);
prompt
prompt alter table inventory_events
prompt   modify event_id generated by default as identity
prompt   (start with limit value);
